from playwright.sync_api import Playwright, sync_playwright


def run(playwright: Playwright) -> None:
    browser = playwright.chromium.launch(headless=False)
    context = browser.new_context()
    page = context.new_page()
    page.goto("https://www.parkingpermitsofamerica.com/PermitRegistration.aspx")
    page.get_by_role("textbox", name="Registration Code*").click()
    page.get_by_role("textbox", name="Registration Code*").fill("MAVP")
    page.get_by_role("button", name=" Verify Code").click()
    page.get_by_role("button", name=" Select").click()
    page.locator('input[name="PermitDetails.LicensePlateNumber"]').click()
    page.locator('input[name="PermitDetails.LicensePlateNumber"]').fill("ABCD1234")
    page.locator('input[name="PermitDetails.LicensePlateNumber"]').press("Tab")
    page.locator('select[name="PermitDetails.LicensePlateState"]').select_option("Texas")
    page.locator('input[name="PermitDetails.VehicleYear"]').click()
    page.locator('input[name="PermitDetails.VehicleYear"]').fill("2025")
    page.locator('input[name="PermitDetails.VehicleMake"]').click()
    page.locator('input[name="PermitDetails.VehicleMake"]').fill("Audi")
    page.locator('input[name="PermitDetails.VehicleMake"]').press("Tab")
    page.locator('input[name="PermitDetails.VehicleModel"]').fill("S5")
    page.locator('input[name="PermitDetails.VehicleModel"]').click()
    page.locator('select[name="PermitDetails.VehicleColor"]').select_option("Red")
    page.locator('input[name="PermitDetails.FirstName"]').click()
    page.locator('input[name="PermitDetails.FirstName"]').fill("John")
    page.locator('input[name="PermitDetails.FirstName"]').press("Tab")
    page.locator('input[name="PermitDetails.LastName"]').fill("Doe")
    page.locator('input[name="PermitDetails.LastName"]').click()
    page.locator('input[name="PermitDetails.LastName"]').fill("Doe")
    page.locator('input[name="PermitDetails.ResidentVisiting"]').click()
    page.locator('input[name="PermitDetails.ResidentVisiting"]').fill("dsakhk")
    page.locator('input[name="PermitDetails.ApartmentVisiting"]').click()
    page.locator('input[name="PermitDetails.ApartmentVisiting"]').fill("dsad")
    page.locator('input[name="PermitDetails.PhoneNumber"]').click()
    page.locator('input[name="PermitDetails.PhoneNumber"]').fill("3123123123123")
    page.locator('input[name="PermitDetails.Email"]').click()
    page.locator('input[name="PermitDetails.Email"]').fill("edads@aol.com")
    page.get_by_role("button", name=" Proceed to Confirmation").click()
    page.locator('input[name="PermitDetails.ApartmentVisiting"]').dblclick()
    page.locator('input[name="PermitDetails.ApartmentVisiting"]').fill("123")
    page.get_by_role("button", name=" Proceed to Confirmation").click()
    page.get_by_role("checkbox", name=" I confirm that I have").check()
    page.get_by_role("button", name=" Confirm and Submit Permit").click()
    page.get_by_text("/15/2025 07:27 PM").click()
    page.get_by_text("3002874").click()
    page.get_by_text("/14/2025 07:27 PM").click()
    page.get_by_text("Red Audi S5").click()
    page.get_by_text("Parking Permits of America is").click()

    # ---------------------
    context.close()
    browser.close()


with sync_playwright() as playwright:
    run(playwright)
